/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.event.KeyEvent;
import java.util.LinkedList;

/**
 *
 * @author pablunsky
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    
    Scope scope;
    
    static int LEFT_CONSTRAINT;
    static int RIGHT_CONSTRAINT;
    static int BOTTOM_CONSTRAINT;
    static int TOP_CONSTRAINT;
    
    public Frame() {
        
        initComponents();
        
        
        LEFT_CONSTRAINT = 0;
        RIGHT_CONSTRAINT = getWidth() - 200;
        BOTTOM_CONSTRAINT = getHeight() - 200;
        TOP_CONSTRAINT = 0;
        
        Character c = new Character(100, 100, 100, 100, "testr.png");
        Underlay u = new Underlay("town.png");
        
        LinkedList<Element> chars = new LinkedList<>();
        
        chars.add(u);
        chars.add(c);
        
        scope = new Scope(chars);
        this.setContentPane(scope);
        
        StartAnim();
        
    }

    public void StartAnim(){
        
        Thread t = new Thread(new Runnable(){
            @Override
            public void run() {
                while(true){
                    scope.repaint();
                    try{
                        Thread.sleep(17);
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                }
            }
        });
        
        t.start();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1468, 816));
        addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                Control(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                Control(evt);
                Stop(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Control(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Control
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                scope.Up();
                break;
            case KeyEvent.VK_DOWN:
                scope.Down();
                break;
            case KeyEvent.VK_RIGHT:
                scope.Right();
                break;
            case KeyEvent.VK_LEFT:
                scope.Left();
                break;
            default:
                break;
        }

        
    }//GEN-LAST:event_Control

    private void Stop(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Stop
        
        scope.Stop();
        
    }//GEN-LAST:event_Stop

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
